//ABANDON ALL HOPE YE WHO ENTER HERE
//ABOVE THE GATES OF HELL
//WHO'S THAT ROLLING THE ROCK UP THE HILL
//NO MAN CAN TELL
//OFFENDED THE GODS WHEN HE WAS ALIVE
//AND SO THEY HAD TO KILL
//AND NOW OLD MAN SISYPHUS KEEPS ROLLING THAT ROCK UP THAT HILL
//BECAUSE WHAT GOES UP
//HAS GOT TO COME DOOOOOOOWN

//is this a reference ANYONE else gets

depth = obj_rock.depth - 1;